### ISSUE TITLE
.NET SDK Error in Blazor wasm self hosted project

### ISSUE THREAD

**Issue by ivoryguard** [TarekNajem04/Jenin.FontAwesome.Blazor#1]
Hello.
I found an issue at Blazor wasm self hosted project.

You can reproduce the issue as the followings;

1. Create a blazor wasm project with out asp.net core hosting
2. Add your nuget package
3. The following error is shown at Error List;

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1082	There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.	MyTestBlazor1	C:\Program Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	430	

Best regards.

**Comment by TarekNajem04** [comment]
Thank you for your support of this project.
The problem has been resolved in the new version 1.2

Best regards.
